org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kotlin.incremental=true

# 本机 SDK 只装了 android-37 平台，这里显式放行，避免 AGP 报 "unsupported compileSdk"
android.suppressUnsupportedCompileSdk=37
android.defaults.buildfeatures.buildconfig=false
android.nonFinalResIds=true
